export const TRANSACTION_TYPES = {
  USER: {
    REGISTER: 'USER REGISTERED',
    LOGIN: 'USER LOGGED IN',
  },
  TASK: {
    COMPLETED: {
      CREATED: 'TASK CREATED',
      UPDATED: 'TASK UPDATED',
      DELETED: 'TASK DELETED',
      QUERIED: 'TASK(S) QUERIED',
    },
    ERROR: {
      CREATE: 'TASK CREATED FAILS',
      UPDATED: 'TASK UPDATED FAILS',
      DELETED: 'TASK DELETED FAILS',
      QUERIED: 'TASK(S) QUERIED FAILS',
    },
  },
};
