export const TRANSACTION_TYPES = {
  USER: {
    REGISTER: 'USER_REGISTERED',
    LOGIN: 'USER_LOGGED',
  },
  TASK: {
    COMPLETED: {
      CREATED: 'TASK_CREATED',
      UPDATED: 'TASK_UPDATED',
      DELETED: 'TASK_DELETED',
    },
    ERROR: {
      CREATE: 'TASK_CREATED_ERROR',
      UPDATED: 'TASK_UPDATED_ERROR',
      DELETED: 'TASK_DELETED_ERROR',
    },
  },
};
